name: Mirror repository

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: frostfox/github-mirror-action
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Mirror
        uses: syzygypl/mirror-action@master
        with:
          originSshKey: ${{ secrets.MIRROR_SSH_KEY }}
          mirrorSshKey: ${{ secrets.ORIGIN_SSH_KEY }}
          mirrorRepoUrl: 'git@github.com:syzygypl/mirror-action-mirror.git'
